# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后台开发', max_length=10, verbose_name='课程类别'),
        ),
    ]
