# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=30, verbose_name='课程标签'),
        ),
    ]
