# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20181030_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='视频链接'),
        ),
    ]
