# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181104_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birhday',
            new_name='birthday',
        ),
    ]
